name: Build with hugo and deploy to zeit
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: spankie/hugo-deploy-to-zeit@master
        env:
          HUGO_VERSION: 0.57.2
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
